name = "photocopie-admin"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "photocopie-admin-db"
database_id = "ca1a0e15-7e38-4eee-afb6-a44b5f6b4418"
