name = "photocopie-admin"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "photocopie-admin"
database_id = "db50c0ee-2e8e-4dfd-a98b-31c100c499e2"

[[r2_buckets]]
binding = "TELECHARGEMENTS"
bucket_name = "photocopie-telechargements"
